Making-my-own-weapon/Coconut-Frontend

src/components/join/ActionCard.tsx, src/components/join/GuestActionContainer.tsx, src/components/join/GuestForm.tsx, src/components/join/HostActionContainer.tsx, src/components/join/HostForm.tsx, src/components/join/api/roomService.ts, src/components/main/FeatureCards.tsx, src/components/main/HeroSection.tsx, src/components/main/MainBackground.tsx, src/pages/JoinPage.tsx, src/pages/MainPage.tsx
closes #17 
-main page구현
-반응형 ui 및 로그인 페이지로 이동 구현
=> feat(#17): mainpage 만들기

src/components/join/ActionCard.tsx, src/components/join/GuestActionContainer.tsx, src/components/join/GuestForm.tsx, src/components/join/HostActionContainer.tsx, src/components/join/HostForm.tsx, src/components/join/api/roomService.ts, src/components/login/LoginCard.tsx, src/components/login/loginApi.ts, src/components/main/FeatureCards.tsx, src/components/main/HeroSection.tsx, src/components/main/MainBackground.tsx, src/pages/JoinPage.tsx, src/pages/LoginPage.tsx, src/pages/MainPage.tsx
closes #21 
- 로그인 API
- 로그인 페이지 구현
=> feat(#21): login page 만들기

src/components/student-class/ProblemPanel/ProblemDetailView.tsx, src/components/teacher-class/ProblemPanel/TeacherProblemDetailView.tsx
문제 표시 컴포넌트 해결했습니다.
기존의 테스트 케이스 테이블은 채점 서버용으로 문제 표시 부분에서는 사용하지 않고, problems 테이블 안에 있는 exampleTc로 표시하도록 하였습니다. 또한 json으로 저장되기 때문에 파싱을 진행하여 올바르게 표시 되도록 하였습니다
문제 표시의 경우, 들여쓰기, 볼드, 줄바꿈이 정상적으로 보이지 않아 보이도록 수정하였습니다
=> fix(#58) : 문제 표시 컴포넌트 수정

package-lock.json, package.json, src/api/client.ts, src/components/join/HostActionContainer.tsx, src/components/join/HostForm.tsx, src/components/student-class/EditorPanel/EditorPanel.tsx, src/components/student-class/Header.tsx, src/components/teacher-class/EditorPanel/EditorPanel.tsx, src/components/teacher-class/grid/GridCard.tsx, src/components/teacher-class/grid/StudentGridView.tsx, src/lib/socket.ts, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx, src/store/teacherStore.ts
closes #57, #63
학생 선택 기능 구현(store) 상태 및 입장인원 제한 수정
동시 편집 에디터 기능 구현
+Chore(#62): .env를 통한 url 진입
.env를 통한 url 진입
=> feat(#57): 동시 편집 에디터 기능 구현

src/components/join/GuestActionContainer.tsx, src/components/signup/SignupCard.tsx, src/components/student-class/EditorPanel/EditorPanel.tsx, src/components/student-class/Header.tsx, src/components/teacher-class/EditorPanel/EditorPanel.tsx, src/components/teacher-class/Header.tsx, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx
=> chore(#66): 자잘한 라벨들 수정

src/App.tsx, src/components/student-class/Header.tsx, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx, src/store/teacherStore.ts
closes #72 
수업나가기 및 그리드뷰 실시간 반영
=> feat(#72): 수업나가기 기능 구현

src/App.tsx, src/api/teacherApi.ts, src/components/report/InfoBox.tsx, src/components/report/MetricCard.tsx, src/components/report/ProblemAnalysisPanel.tsx, src/components/report/ReportHeader.tsx, src/components/report/StudentPerformancePanel.tsx, src/components/report/index.ts, src/components/student-class/Header.tsx, src/pages/ReportPage.tsx, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx, src/store/teacherStore.ts
closes (#71)
방 폭파 되서 이제 생성자는 방을 다시 만들 수 있게 되었습니다.
리포트 페이지는 아직 기능 구현이 되지 않았습니다.
=> Feat: 방 폭파 구현, 리포트 페이지 생성

src/components/common/SvgOverlay.tsx, src/components/student-class/EditorPanel/EditorPanel.tsx, src/components/teacher-class/EditorPanel/EditorPanel.tsx, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx
=> feat: 그림판 동기화 진짜 완성

src/components/student-class/EditorPanel/EditorPanel.tsx, src/components/teacher-class/EditorPanel/EditorPanel.tsx, src/index.css, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx, src/store/studentStore.ts, src/store/teacherStore.ts
* 대원이의 그림판과 로컬에서 머지 후 올립니다.
* 선생님과, 학생 둘의 에디터 패널 파일에서 (그림판, 커서) onMount 함수를 하나로 합침
=> feat(#94): 실시간 커서 보여주기 기능 개발

package-lock.json, package.json, src/components/common/VoiceChatModal.tsx, src/components/common/logoutApi.ts, src/components/student-class/Header.tsx, src/components/teacher-class/Header.tsx, src/hooks/useVoiceChat.ts, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx, vite.config.ts
- **React + simple-peer 기반 WebRTC 음성채팅 기능 도입**
- 헤더 마이크 버튼 클릭 시 팝업(VoiceChatModal)로 음성채팅 UI 제공
- 참가자별 음소거, 볼륨 조절, 내 마이크 on/off, 퇴장 등 컨트롤 지원
- 실시간 참여자 목록 동기화 및 각 참여자별 오디오 스트림 관리
- WebRTC 연결: 1:1~3명은 P2P, 4~5명은 SFU(서버 중계) 하이브리드 구조 준비
- STUN 서버 다중 등록(trickle ICE)로 연결 안정성 강화
- 데이터 채널 협상 꼬임 방지(불필요한 데이터 채널 닫기)
- 볼륨 동기화, 음소거, UI/UX 개선
- 중복 피어/스트림/연결 방지 로직 강화
- 참가자 stream을 participant 객체에 포함, `<audio>`로 직접 재생
- React Strict Mode, 이벤트 리스너 중복, 시그널링 꼬임 등 주요 이슈 해결
---
- **useVoiceChat 커스텀 훅**
- 마이크 상태, 피어 연결, 소켓 시그널링, 오디오 스트림 관리
- 참가자별 stream을 participant에 할당하여 UI에서 직접 `<audio>`로 재생
- 볼륨/음소거/퇴장 등 상태 관리 및 UI 연동
- **VoiceChatModal 컴포넌트**
- 내 마이크/볼륨/음소거, 참여자별 볼륨/음소거 UI 제공
- 각 참여자별 오디오 스트림 `<audio>`로 재생(숨김)
- 중복 참가자/피어/스트림 방지
- **WebRTC 연결 안정화**
- initiator 자동 분기(내 userId < 상대방이면 initiator: true)
- …
=> feat(#103): 음성 채팅 기능 개발

src/api/detailedAnalysisApi.ts, src/api/realtimeAnalysisApi.ts, src/components/analysis/StaticAnalysisReport.tsx, src/components/teacher-class/AnalysisPanel.tsx, src/hooks/useRealtimeAnalysis.ts, src/pages/TeacherClassPage.tsx, src/store/submissionStore.ts
- API 추가
- 디자인 수정
- API 호출 후 결과 표시
=> feat(#110): LLM  기능 구현 - 실시간

src/components/student-class/EditorPanel/EditorPanel.tsx, src/components/teacher-class/EditorPanel/EditorPanel.tsx, src/components/teacher-class/ProblemPanel/TeacherProblemDetailView.tsx, src/components/teacher-class/ProblemPanel/TeacherProblemListView.tsx, src/components/teacher-class/ProblemPanel/TeacherProblemPanel.tsx, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx, src/store/studentStore.ts, src/store/teacherStore.ts
closes #126 
협업시에 선생님이 다른 문제들도 열람할수있도록 수정
커서는 같은 문제를 보고있을때만 보이도록 개발
=> fix(#126): 협업 ui/ux 개선

src/analysis/syntaxChecker.ts, src/hooks/useRealtimeAnalysis.ts
- 코드분석이 켜져있는 상태에서 채점을 하면 오류가 발생했던 것.
=> fix(#141): pyodide 로딩 해결

src/App.tsx, src/pages/NotFoundPage.tsx, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx, src/store/studentStore.ts, src/store/teacherStore.ts
closes #147 
잘못된 url일경우 오류페이지 구현했습니다
=> feat(#147): 오류페이지 구현

src/components/report/BoardReportStudent.tsx, src/components/report/StudentReportDashboardView.tsx, src/components/report/StudentReportView.tsx, src/pages/StudentReportPage.tsx
close #156 
1.  선생님이 보는 학생 리포트에서 드롭 다운을 제거한 버전입니다.
2. 드롭다운이 제거된 자리에 학생이름과 몇 문제를 맞췄는지 표시되게 했습니다.
3. 지금은 나가기 버튼이 없고 깡통인 리포트 저장버튼만 있는데 추후에 수정하겠습니다.
=> feat(#156): 학생 페이지 상세분석 개발

src/components/teacher-class/grid/GridCard.tsx, src/components/teacher-class/grid/StudentGridView.tsx, src/pages/StudentClassPage.tsx, src/store/teacherStore.ts
closes #162 
그리드뷰 개선
풀고있는 문제 연결
=> feat(#162): 그리드뷰 개선

package-lock.json, src/api/userApi.ts, src/components/mypage/AccountManagementView.tsx, src/components/mypage/PasswordChangeModal.tsx, src/components/signup/SignupCard.tsx, src/components/student-class/Header.tsx, src/components/teacher-class/Header.tsx, src/pages/MyPage.tsx, src/store/authStore.ts
비밀 번호 변경 모달 제작 및 변경 기능 구현
회원 가입 시 alert 변경
불필요한 alert 삭제
=> feat(#164): 비밀번호 변경 구현 및 alert 수정

src/components/teacher-class/grid/GridCard.tsx, src/components/teacher-class/grid/StudentGridView.tsx, src/pages/StudentClassPage.tsx, src/store/guestStore.ts, src/store/submissionStore.ts, src/store/teacherStore.ts
=> feat(#162): 그리드뷰 개선 최종

src/api/reportApi.ts, src/components/mypage/MyPageReportBox.tsx, src/components/mypage/SavedReportsView.tsx, src/components/report/StudentReportDashboardView.tsx, src/pages/ReportPage.tsx, src/pages/StudentReportPage.tsx
리포트 저장 버튼 누르면 DB에 저장까지 가능합니다. 
이제 mypage에 저장된 리포트 목록 표시하고 상세 보기 클릭 시 리포트 페이지 그대로 구현할 예정입니다.
=> feat: 리포트 저장 버튼 누르면 DB에 저장까지 구현

src/components/mypage/SavedReportsView.tsx, src/components/report/StudentReportDashboardView.tsx, src/components/teacher-class/Header.tsx, src/pages/ReportPage.tsx, src/pages/SavedReportDetailPage.tsx, src/pages/StudentClassPage.tsx, src/pages/TeacherClassPage.tsx
1. 마이페이지에서 리포트 이름 흰색에서 검은 색으로 변경
2. 리포트 내역에서 상세보기, 삭제 버튼 디자인 변경
3. 리포트 삭제할 때 alert -> sweetAlert 변경
4. 리포트 페이지에서 리포트 저장하지 않고 나갈 때 리포트 저장 안하고 나갈 것인지 표시하는 alert 창 추가
5. 리포트 페이지와 마이페이지 리포트 차트 모양 수정
=> fix: 리포트 버그 수정

src/analysis/complexityAnalyzer.ts, src/components/analysis/StaticAnalysisReport.tsx
실시간 정규식 분석
-----------
1. **실시간 코드 품질 지표 카드의 번쩍임(플리커링) 개선**
- 코드 품질 지표 카드(StaticAnalysisReport)의 min-height를 300px로 고정하여,  
분석 결과가 없거나 문법 오류가 적어도 카드 크기가 일정하게 유지되도록 개선했습니다.
- 카드 내부 내용이 바뀔 때(로딩/결과 전환 등) 높이가 줄어들지 않아 UI가 안정적으로 보입니다.
2. **로딩 중에도 이전 분석 결과 유지**
- 분석 요청(loading) 중에도 이전 분석 결과를 잠깐 유지하도록 하여,  
분석 결과가 null이 되는 순간에도 카드 내부가 비지 않고  
번쩍임 없이 부드럽게 상태가 전환되도록 개선했습니다.
3. **'실시간 분석 중...' 메시지 제거**
- loading 상태에서 "실시간 분석 중..." 메시지를 아예 표시하지 않도록 하여  
카드가 줄어들었다가 다시 커지는 현상(깜빡임)을 방지했습니다.
4. **중첩 루프 등 복잡도 판정 정확도 개선**
- complexityAnalyzer에서 전역 코드(함수 밖)도 중첩 루프 깊이에 따라  
시간복잡도가 O(n), O(n²), O(n³) 등으로 정확히 판정되도록 개선했습니다.
실시간 LLM 분석
----------
1. **실시간 LLM 분석 패널(실시간 AI 분석 카드) 최소 0.5초 로딩 딜레이 적용**
- AI 분석 결과가 너무 빨리(특히 캐시 히트 시) 도착하면  
최소 0.5초 동안은 로딩 상태가 유지되도록 하여  
UX가 더 자연스럽고, 번쩍임이 줄어들도록 개선했습니다.
---
=> fix(#191): 실시간 분석 패널 번쩍거림 해결

src/components/report/StudentReportView.tsx, src/pages/JoinPage.tsx
=> fix(#193): 학생 리포트 뷰 롤백

src/pages/SavedReportDetailPage.tsx, src/pages/StudentReportPage.tsx, src/store/reportStore.ts
1. 학생 리포트 페이지 정답률 오류 수정했습니다
2. 학생 리포트 페이지 첫 제출 시 문제 수 수정했습니다.
3. 마이페이지 학생 리포트에도 적용되게 수정했습니다..
=> fix: 학생 리포트 로직 수정

src/components/mypage/MyPageReportBox.tsx, src/components/mypage/ProblemManagementView.tsx, src/utils/sweetAlert.ts
=> fix(#207): 알럿 버그

src/components/teacher-class/EditorPanel/EditorPanel.tsx, src/components/teacher-class/grid/StudentGridView.tsx, src/pages/TeacherClassPage.tsx
=> fix(#209,#210): 그리드 수정 및 선생 에디터 스크롤 수정

src/components/student-class/ProblemPanel/ProblemDetailView.tsx, src/components/teacher-class/ProblemPanel/ProblemCreateForm.tsx
closes #215 
테스트 케이스가 값이 아닌 경로가 표시되는 문제해결
=> fix(#215):학생 테스트 케이스 표시문제 해결

README.md
=> [fix]Update README.md
